# This file contains values from Cookiecutter

default_context:
  project_name: "Flow-MS"
  repo_name: "Flow-MS"
  description: "A short description of the project. No quotes."
  organization: "TUE"
  license: "MIT"
  organization_email: "none@none.pt"
  line_length: "120"
  python_minimal_version: "3.10"
